apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: main-rules
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: prometheus
spec:
  groups:
    - name: main.rules
      rules:
      - alert: HostHighCpuLoad
        expr: (100 - (avg by(instance) (rate(node_cpu_seconds_total{mode ="idle"}[2m])) *100)) > 40
        for: 2m
        labels:
          severity: warning
          namespace: monitoring
        annotations:
          describtion: "Cpu load on host is over 50%\n value = {{$value}}\n instance = {{$labels.instance}}\n"
          summary: "Host High Cpu Load"

      - alert: K8sPodCrashLooping
        expr: kube_pod_container_status_restarts_total >= 4
        for: 0m
        labels:
          severity: critical
          namespace: monitoring
        annotations:
          describtion: "Pod {{$labels.pod}} is crash looping\n value = {{$value}}\n instance = {{$labels.instance}}"
          summary: "K8s Pod Crash Looping"