---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/omarnabil1998/Continuous-deployment.git
      targetRevision: HEAD
      path: K8s/Monitoring
    - repoURL: https://prometheus-community.github.io/helm-charts/
      chart: prometheus-mongodb-exporter
      targetRevision: 3.1.3
      helm:
        version: v3
        releaseName: mongo-exporter
        passCredentials: false
        values: |
          mongodb:
            uri: "mongodb://mongodb-0.mongodb-service.application:27017"
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true