---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: knote-cluster
  namespace: istio-ingress
spec:
  dnsNames:
  - 'knote-cluster.duckdns.org'
  issuerRef:
    name: cert-manager-webhook-duckdns-production
    kind: ClusterIssuer
  secretName: knote-cluster.duckdns.org-tls-secret-production
