- name: Getting jenkins initial password
  hosts: server_jenkins
  become: true
  tasks:
    - name: Getting jenkins initial password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
    - debug: msg={{jenkins_password.stdout_lines}}

- name: Getting nexus initial password
  hosts: server_nexus
  become: true 
  tasks:
    - name: Getting nexus initial password
      shell: cat /opt/sonatype-work/nexus3/admin.password
      register: nexus_password
    - debug: msg={{nexus_password.stdout_lines}}