apiVersion: v1
kind: Service
metadata:
  name: knote-service
  namespace: application
spec:
  selector:
    app: knote
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      imagePullSecrets:
        - name: my-registry-key
      containers:
        - name: knote
          image: $DOCKER_REPO/$KNOTE_APP
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: database-url
          imagePullPolicy: Always
